// client/src/components/Base/Footer.tsx
import { _Link as Link } from "../Link"

export function Footer() {
  const currentYear = new Date().getFullYear()

  return (
    <footer className="px-6 pt-12 pb-6 mx-auto max-w-screen-2xl space-y-3.5">
      <div className="flex items-center justify-between gap-x-2">
        <p className="text-xs">
          <span className="opacity-75">{`© 2024-${currentYear} `}</span>
          <Link href="https://kurojifusky.com">Kuroji Fusky</Link>
          <span className="opacity-75">
            {". Licensed under the "}
          </span>
          <Link href="https://opensource.org/license/mit">MIT</Link>
          <span className="opacity-75">{" license."}</span>
        </p>
        <div className="space-x-3.5">
          <Link className="inline-flex items-center" href="/about">
            About
          </Link>
          <Link
            className="inline-flex items-center"
            href="https://github.com/kuroji-fusky/SponsorExplorer"
          >
            Source code
          </Link>
        </div>
      </div>
    </footer>
  )
}

// client/src/routes/footer.svelte
<script lang="ts">
  import { Link } from "$lib/components";

  const footerLinks = [
    { href: "/docs", text: "Docs" },
    { href: "/about", text: "About" },
    { href: "https://github.com/kuroji-fusky/SponsorExplorer", text: "Source code" },
  ];
</script>

<footer
  class="py-4 px-6 flex items-center justify-between max-w-screen-2xl mx-auto w-full"
>
  <span class="text-xs">
    {"© 2024-2026 "}<Link
      href="https://kurojifusky.com/"
      rel="noopenner noreferrer"
      target="_blank"
    >
      {"Kuroji Fusky"}
    </Link>{"; MIT licensed"}
  </span>
  <div class="inline-flex gap-x-4">
    {#each footerLinks as { href, text }}
      <Link {href}>{text}</Link>
    {/each}
  </div>
</footer>
