// src/lib/components/Table/SegmentTableRow.svelte
<script lang="ts">
  import type { SBSegmentData } from "$lib/types"
  import { cn } from "$lib/utils"
  import {
    EyeOffIcon,
    LockIcon,
    TimerOffIcon,
    XCircleIcon
  } from "lucide-svelte"
  import { LengthBadge, SegmentBadge } from "../Badges"

  export let item: SBSegmentData

  const isDownvoted = item.votes <= -2
  const hiddenIndicator = isDownvoted || item.isHidden || item.isShadowHidden
</script>

<tr
  class={cn(
    "border-b border-neutral-800",
    hiddenIndicator
      ? "opacity-30 hover:opacity-100 grayscale-[.75] hover:grayscale-0"
      : null
  )}
>
  <td id="submitted-date">
    <time datetime={item.submittedDate}>
      {item.submittedDateReadable}
    </time>
  </td>

  <td id="votes">
    <div class="flex items-center gap-x-1.5">
      <span>{item.votes}</span>
      {#if item.isLocked}
        <div class="cursor-help" title="Segment has been locked by a VIP">
          <LockIcon class="text-yellow-500" size={18} />
        </div>
      {/if}
    </div>
  </td>

  <td id="views">
    <div class="flex items-center gap-x-1.5">
      <span>
        {item.segmentAction !== "full" ? item.views : "—"}
      </span>
      {#if isDownvoted}
        <div
          class="text-red-500 cursor-help"
          title="Segment not shown from downvotes"
        >
          <XCircleIcon size={18} />
        </div>
      {/if}
      {#if item.isShadowHidden}
        <div
          class="text-red-500 cursor-help"
          title="Segment has been shadowhidden"
        >
          <EyeOffIcon size={18} />
        </div>
      {/if}
      {#if item.isHidden}
        <div
          class="text-red-500 cursor-help"
          title="Segment is hidden from video duration change"
        >
          <TimerOffIcon size={18} />
        </div>
      {/if}
    </div>
  </td>
  <td id="segment">
    <SegmentBadge
      segment={item.segmentLabel}
      chapterLabel={item.chapterLabel}
    />
  </td>
  <td id="length">
    <LengthBadge
      actionType={item.segmentAction}
      startTime={item.startTime}
      endTime={item.endTime}
    />
  </td>
  <td id="username-userid">
    <div class="overflow-ellipsis overflow-hidden w-48">
      {item.userid}
    </div>
  </td>
</tr>

// src/components/Tables/SegmentTableRow.tsx
"use client"

import { useState, useRef, useCallback } from "react"
import type { Category } from "@/utils/SponsorBlock.types"
import { SegmentBadge } from "../Badges"
import {
  LuCopy,
  LuEyeOff,
  LuFilter,
  LuLock,
  LuTimerOff,
  LuXCircle,
} from "react-icons/lu"
import { cn, formatNumber, mapCategory, parseDateStr } from "@/utils"
import { LengthBadge } from "../Badges/LengthBadge"
import type { Segment } from "./SegmentRow.types"
import { SegmentRowDropdown } from "./SegmentRowDropdown"

interface SegmentTableRowProps extends Segment {}

export function SegmentTableRow(props: SegmentTableRowProps) {
  const { isoDate, readableDate } = parseDateStr(props.timeSubmitted)

  const [isHovering, setHoverState] = useState(false)
  const tableRowRef = useRef<React.ComponentRef<"tr">>(null)

  const handleRowEnter = useCallback(() => setHoverState(true), [])
  const handleRowLeave = useCallback(() => setHoverState(false), [])

  const hoverOptionsCn = cn("flex ml-1", isHovering ? undefined : "opacity-0")

  const { label: segmentLabel } = mapCategory(props.category)

  return (
    <tr
      ref={tableRowRef}
      onMouseEnter={handleRowEnter}
      onMouseLeave={handleRowLeave}
      onBlur={handleRowLeave}
      className={cn(
        props.shadowHidden || props.hidden || props.votes <= -2
          ? "opacity-50 hover:opacity-100"
          : undefined,
        "hover:bg-neutral-300/40 dark:hover:bg-neutral-800/40",
      )}
    >
      {/* Date submitted */}
      <td>
        <time dateTime={isoDate} className="whitespace-nowrap">
          {readableDate}
        </time>
      </td>

      {/* Votes */}
      <td>
        <div className="inline-flex items-center gap-x-1">
          <span>{formatNumber(props.votes)}</span>
          {props.locked ? (
            <LuLock size={17} className="text-yellow-400" />
          ) : null}
        </div>
      </td>

      {/* Views */}
      <td>
        <div className="inline-flex items-center gap-x-1">
          <span>
            {props.actionType === "full" ? "—" : formatNumber(props.views)}
          </span>
          {props.shadowHidden ? (
            <LuEyeOff size={17} className="text-red-500" />
          ) : null}
          {props.hidden ? (
            <LuTimerOff size={17} className="text-red-500" />
          ) : null}
          {props.votes <= -2 ? (
            <LuXCircle size={17} className="text-red-500" />
          ) : null}
        </div>
      </td>

      {/* Segment/category */}
      <td>
        <div className="flex items-center gap-x-0.5">
          <SegmentBadge
            segments={props.category as Category}
            chapterLabel={props.description}
            layout="desktop"
          />
          <div className={hoverOptionsCn}>
            <button
              className="p-0.5"
              title={`Filter out the ${segmentLabel} category (Alt+Click to negate)`}
            >
              <LuFilter size={19} />
            </button>
            <button className="p-0.5">
              <LuCopy size={19} />
            </button>
          </div>
        </div>
      </td>

      {/* Length */}
      <td>
        <LengthBadge
          actionType={props.actionType}
          endTime={props.endTime}
          startTime={props.startTime}
        />
      </td>

      {/* Username/UserID */}
      <td>
        <div className="flex items-center gap-x-0.5 max-w-48">
          <div className="truncate flex-1">
            <span>{props.userID}</span>
          </div>
          <div className={hoverOptionsCn}>
            <button className="p-0.5">
              <LuFilter size={19} />
            </button>
            <button className="p-0.5">
              <LuCopy size={19} />
            </button>
          </div>
        </div>
      </td>

      {/* More actions */}
      <td>
        <div className={hoverOptionsCn}>
          <SegmentRowDropdown />
        </div>
      </td>
    </tr>
  )
}
