// client/src/components/Headers/ChannelInfo.tsx
"use client"

import { _Link as Link } from "../Link"
import { LuBookmark, LuExternalLink } from "react-icons/lu"
import { SegmentStatsInline } from "../SegmentStatsInline"
import { useChannelStoreProvider } from "@/context"

export function ChannelInfo() {
  const { channel } = useChannelStoreProvider()

  return (
    <div className="mt-1 flex bg-neutral-100 dark:bg-neutral-800/30 rounded-md px-7 py-6 gap-x-5">
      <div className="flex-shrink-0">
        <div className="size-32 relative overflow-hidden rounded-full">
          <img src={`${channel.thumbs}`} alt="" className="size-full" />
        </div>
      </div>
      {/* Details */}
      <div className="flex-1 flex flex-col gap-y-2">
        {/* Channel title */}
        <div className="space-y-1.5">
          <span className="opacity-75">Segments for channel</span>
          <div className="flex flex-wrap items-center">
            <span className="text-2xl font-bold inline" translate="no">
              {channel.channelName}
            </span>
            <button className="ml-1 p-2 inline">
              <LuBookmark size={18} />
            </button>
            <Link
              href={`https://www.youtube.com/channel/${channel.id}`}
              className="p-2 inline"
            >
              <LuExternalLink size={17} />
            </Link>
          </div>
        </div>
        {/* Segments submitted */}
        <SegmentStatsInline />
      </div>
    </div>
  )
}

// client/src/lib/components/panels/ChannelInfo.svelte
<script lang="ts">
  import { BookmarkIcon, EllipsisIcon, ExternalLinkIcon } from "@lucide/svelte";
  import Button from "../Button.svelte";
  import { getChannelMeta } from "$lib/context";

  const { name, videoCount, avatar } = getChannelMeta();
</script>

<div id="channel-info-panel" class="flex items-center">
  <img
    src={avatar}
    alt={`Channel avatar for ${name}`}
    class="size-32 aspect-square rounded-xl bg-red-50 mr-4 pointer-events-none"
    draggable="false"
  />
  <div class="flex-1 flex flex-col gap-y-1">
    <span class="opacity-60">Channel segments for</span>
    <h1 class="font-bold text-3xl" translate="no">{name}</h1>
    <div class="inline-flex items-center gap-x-1 mt-2">
      <span>{`${videoCount} videos`}</span>
      <!-- Separator -->
      <hr class="mx-1 h-4 border border-l opacity-50" />

      <!-- Actions -->
      <Button href="/#">
        <span>Visit channel</span>
        {#snippet suffix()}
          <ExternalLinkIcon size={16} />
        {/snippet}
      </Button>
      <Button>
        {#snippet prefix()}
          <BookmarkIcon size={17} />
        {/snippet}
        Save
      </Button>
      <Button icon>
        <EllipsisIcon size={17} />
      </Button>

      <!-- Consolidate options as dropdowns instead -->
      <!-- <div class="rounded-md border inline-flex items-center">
        <button class="hover:bg-white/20 px-2 py-1">Share</button>
        <button
          class="hover:bg-white/20 p-1 border border-l-neutral-600 border-transparent"
        >
          <ChevronDown size={15} />
        </button>
      </div>
      <div class="rounded-md border inline-flex items-center">
        <button class="hover:bg-white/20 px-2 py-1">Copy</button>
        <button
          class="hover:bg-white/20 p-1 border border-l-neutral-600 border-transparent"
        >
          <ChevronDown size={15} />
        </button>
      </div> -->
    </div>
  </div>
</div>
