// src/components/Headers/ChannelInfo.tsx
"use client"

import { _Link as Link } from "@/components/Link"
import { LuBookmark, LuExternalLink } from "react-icons/lu"
import { SegmentStatsInline } from "../SegmentStatsInline"

interface ChannelInfoProps {
  channelId: string
}

export function ChannelInfo(props: ChannelInfoProps) {
  return (
    <div className="mt-1 flex bg-neutral-100 dark:bg-neutral-900/40 rounded-md px-6 py-5 gap-x-5">
      <div className="flex-shrink-0">
        <div className="size-28 rounded-full bg-red-300" />
      </div>
      {/* Details */}
      <div className="flex-1 flex flex-col gap-y-2">
        {/* Channel title */}
        <div className="space-y-0.5">
          <span className="opacity-75">Segments for channel</span>
          <div className="flex flex-wrap items-center">
            <span className="text-2xl font-bold inline" translate="no">
              Channel Name
            </span>
            <button className="ml-1 p-2 inline">
              <LuBookmark size={18} />
            </button>
            <Link
              href={`https://www.youtube.com/channel/${props.channelId}`}
              className="p-2 inline"
            >
              <LuExternalLink size={17} />
            </Link>
          </div>
        </div>
        {/* Segments submitted */}
        <SegmentStatsInline />
      </div>
    </div>
  )
}

// client/src/lib/components/panels/ChannelInfo.svelte
<script lang="ts">
  import { BookmarkIcon, ChevronDown, ExternalLinkIcon } from "@lucide/svelte";

  interface Props {}

  const {}: Props = $props();
</script>

<div id="channel-info-panel" class="flex items-center">
  <div class="size-32 aspect-square rounded-xl bg-red-50 mr-4"></div>
  <div class="flex-1 flex flex-col gap-y-1">
    <span class="opacity-60">Channel segments for</span>
    <h1 class="font-bold text-2xl" translate="no">((channel name))</h1>
    <div class="inline-flex items-center gap-x-1.5 mt-2">
      <span># videos</span>
      <!-- Separator -->
      <hr class="mx-1 h-4 border border-l opacity-50" />

      <!-- Actions -->
      <a
        href="/#"
        class="hover:bg-white/20 px-2 py-1 rounded-md border inline-flex items-center gap-x-1 *:whitespace-nowrap"
      >
        <span>Visit channel</span>
        <ExternalLinkIcon size={15} />
      </a>
      <button
        class="hover:bg-white/20 px-2 py-1 rounded-md border inline-flex items-center gap-x-1"
      >
        <BookmarkIcon size={15} />
        <span> Save </span>
      </button>
      <div class="rounded-md border inline-flex items-center">
        <button class="hover:bg-white/20 px-2 py-1">Share</button>
        <button
          class="hover:bg-white/20 p-1 border border-l-neutral-600 border-transparent"
        >
          <ChevronDown size={15} />
        </button>
      </div>
      <div class="rounded-md border inline-flex items-center">
        <button class="hover:bg-white/20 px-2 py-1">Copy</button>
        <button
          class="hover:bg-white/20 p-1 border border-l-neutral-600 border-transparent"
        >
          <ChevronDown size={15} />
        </button>
      </div>
    </div>
  </div>
</div>
