// src/lib/components/Table/SegmentTable.svelte
<script lang="ts">
  import Col from "./Col.svelte"

  const colData = [
    { id: "submitted-date", width: 14, label: "Submitted Date" },
    { id: "votes", width: 5, label: "Votes" },
    { id: "views", width: 6, label: "Views" },
    { id: "segment", width: 15, label: "Category" },
    { id: "length", width: 15, label: "Length" },
    { id: "username-userid", width: 16, label: "Username/UserID" }
  ]
</script>

<table class="w-full text-base *:[&_tr]:py-2.5 *:[&_tr]:px-3">
  <colgroup>
    {#each colData as { id, width }}
      <Col {id} {width} />
    {/each}
  </colgroup>
  <thead>
    <tr class="border-b border-slate-500 *:text-left">
      {#each colData as { id, label }}
        <th {id}>{label}</th>
      {/each}
    </tr>
  </thead>
  <tbody class="hover:[&_tr]:bg-neutral-800 hover:[&_tr]:bg-opacity-70">
    <slot />
  </tbody>
</table>

// client/src/components/Tables/SegmentTable.tsx
import type { VideoSegments } from "@/types"
import { SegmentTableRow } from "./SegmentTableRow"
import { SegmentRowMobile } from "./SegmentRowMobile"

interface SegmentTableProps extends Pick<VideoSegments, "segments"> {
  selectMode?: boolean
}

export function SegmentTable(props: SegmentTableProps) {
  return (
    <>
      <table className="hidden lg:table w-full *:[&_tr]:px-2 *:[&_tr]:py-2.5 [&_td]:border-b [&_td]:border-neutral-200 dark:[&_td]:border-neutral-700 text-base">
        <colgroup>
          <col style={{ width: "25%" }} />
          <col style={{ width: "9%" }} />
          <col style={{ width: "9%" }} />
          <col style={{ width: "25%" }} />
          <col style={{ width: "99%" }} />
          <col style={{ width: "12%" }} />
          <col style={{ width: "1%" }} />
        </colgroup>
        <thead className="*:text-left">
          <tr className="sticky top-28 z-20 se-bg-w1">
            <th>
              <span className="whitespace-nowrap">Date submitted</span>
            </th>
            <th>
              <span className="whitespace-nowrap">Votes</span>
            </th>
            <th>
              <span className="whitespace-nowrap">Views</span>
            </th>
            <th>
              <span className="whitespace-nowrap">Category</span>
            </th>
            <th>
              <span className="whitespace-nowrap">Length</span>
            </th>
            <th>
              <span className="whitespace-nowrap">Username/UserID</span>
            </th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {props.segments.map((segment) => (
            <SegmentTableRow key={segment.UUID} {...segment} />
          ))}
        </tbody>
      </table>
      <div className="mt-3 block lg:hidden">
        {props.segments.map((segment) => (
          <SegmentRowMobile key={segment.UUID} {...segment} />
        ))}
      </div>
    </>
  )
}
