// client/src/components/Tables/SegmentTable.tsx
import type { VideoSegments } from "@/types"
import { SegmentTableRow } from "./SegmentTableRow"
import { SegmentRowMobile } from "./SegmentRowMobile"

interface SegmentTableProps extends Pick<VideoSegments, "segments"> {
  selectMode?: boolean
}

export function SegmentTable(props: SegmentTableProps) {
  return (
    <>
      <table className="hidden lg:table w-full *:[&_tr]:px-2 *:[&_tr]:py-2.5 [&_td]:border-b [&_td]:border-neutral-200 dark:[&_td]:border-neutral-700 text-base">
        <colgroup>
          <col style={{ width: "25%" }} />
          <col style={{ width: "9%" }} />
          <col style={{ width: "9%" }} />
          <col style={{ width: "25%" }} />
          <col style={{ width: "99%" }} />
          <col style={{ width: "12%" }} />
          <col style={{ width: "1%" }} />
        </colgroup>
        <thead className="*:text-left">
          <tr className="sticky top-28 z-20 se-bg-w1">
            <th>
              <span className="whitespace-nowrap">Date submitted</span>
            </th>
            <th>
              <span className="whitespace-nowrap">Votes</span>
            </th>
            <th>
              <span className="whitespace-nowrap">Views</span>
            </th>
            <th>
              <span className="whitespace-nowrap">Category</span>
            </th>
            <th>
              <span className="whitespace-nowrap">Length</span>
            </th>
            <th>
              <span className="whitespace-nowrap">Username/UserID</span>
            </th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {props.segments.map((segment) => (
            <SegmentTableRow key={segment.UUID} {...segment} />
          ))}
        </tbody>
      </table>
      <div className="mt-3 block lg:hidden">
        {props.segments.map((segment) => (
          <SegmentRowMobile key={segment.UUID} {...segment} />
        ))}
      </div>
    </>
  )
}

// client/src/lib/components/Table/SegmentTable.svelte
<script lang="ts">
  import Col from "./Col.svelte"

  export let data: object[] = [{}]
</script>

<table data-segment-table="" class="w-full text-base">
  <colgroup>
    <Col id="submitted-date" width={15} />
    <Col id="username-userid" width={20} />
    <Col id="length" width={15} />
    <Col id="segment" width={15} />
    <Col id="votes" width={8} />
    <Col id="views" width={8} />
    <Col id="is-hidden" width={8} />
  </colgroup>
  <thead>
    <tr class="border-b border-slate-500 *:text-left">
      <th id="submitted-date">Submitted Date</th>
      <th id="username-userid">Username/UserID</th>
      <th id="length">Length</th>
      <!-- TODO: Add uuid stuff in this column as copiable -->
      <th id="segment">Segment</th>
      <th id="votes">Votes</th>
      <th id="views">Views</th>
      <th id="is-hidden">Hidden?</th>
    </tr>
  </thead>
  <tbody>
    <slot />
  </tbody>
</table>

<style lang="postcss">
  :global([data-segment-table] :is(th, td)) {
    @apply py-2.5 px-3;
  }
</style>
