// src/lib/components/Base/Footer.svelte
<script>
  import Link from "../Link.svelte"
  import ExternalLink from "lucide-svelte/icons/external-link"

  const currentYear = new Date().getFullYear()
</script>

<footer class="mt-4 bg-neutral-900 border-t border-neutral-600">
  <div class="px-6 py-8 mx-auto max-w-screen-2xl">
    <article class="last:prose-p:mb-0 prose-p:mb-1.5">
      <p>
        <strong>SponsorExplorer</strong> is a modern rewrite of
        <Link href="https://sb.ltn.fi" external>SBbrowser</Link> with additional
        features and an intuitive UI!
      </p>
    </article>
    <div
      class="pt-3 border-t border-neutral-400 mt-4 flex items-center gap-x-2"
    >
      <span class="flex-1"
        >{`© ${currentYear} Kerby Keith Aquino; licensed under MIT`}</span
      >
      <Link
        class="inline-flex items-center"
        href="https://github.com/kurojifusky/SponsorExplorer"
        external
      >
        <span>Source code</span>
        <ExternalLink size={17} class="ml-1" />
      </Link>
    </div>
  </div>
</footer>

// src/components/Base/Footer.tsx
import { _Link as Link } from "../Link"
import { LuExternalLink } from "react-icons/lu"

export function Footer() {
  const currentYear = new Date().getFullYear()

  return (
    <div className="mt-4 dark:bg-neutral-900 border-t border-neutral-600">
      <footer className="px-6 py-7 mx-auto max-w-screen-2xl">
        <div className="flex items-center gap-x-2">
          <div className="flex-1 space-x-3.5">
            <Link className="inline-flex items-center" href="/about">
              About
            </Link>
            <Link
              className="inline-flex items-center"
              href="https://github.com/kuroji-fusky/SponsorExplorer"
            >
              Source
            </Link>
            <span className="font-mono">DEVELOPMENT</span>
          </div>

          <span>
            {`© ${currentYear} `}
            <Link
              className="no-underline inline-flex items-center"
              href="https://kuroji.fusky.pet"
            >
              Kuroji Fusky, licensed under Apache-2.0
            </Link>
          </span>
        </div>
      </footer>
    </div>
  )
}
