// src/lib/components/Base/Navbar.svelte
<script lang="ts">
  import { onMount } from "svelte"
  import BookmarkIcon from "lucide-svelte/icons/bookmark"
  import SearchIcon from "lucide-svelte/icons/search"
  import SettingsIcon from "lucide-svelte/icons/settings"
  import ChevronDownIcon from "lucide-svelte/icons/chevron-down"
  import ServerIcon from "lucide-svelte/icons/server"
  import MenuIcon from "lucide-svelte/icons/menu"

  import Button from "../Button.svelte"
  import Watchlist from "./Sidebar/Watchlist.svelte"
  import Options from "./Sidebar/Options.svelte"
  import { optionToggle, watchlistToggle } from "$lib/stores"
</script>

<nav
  class="px-8 flex justify-between py-4 items-center sticky top-0 bg-neutral-950 z-10 *:flex"
>
  <div class="items-center gap-x-4">
    <a href="/"
      ><span class="font-bold text-xl" translate="no">SponsorExplorer</span></a
    >
    <Button
      title="Search"
      class="hidden md:flex items-center gap-x-1.5 py-1.5 px-3 !bg-transparent !border border-neutral-500 hover:border-neutral-300 w-48"
    >
      <SearchIcon size={18} />
      <span class="opacity-50">Search...</span>
    </Button>
  </div>

  <div class="gap-x-1">
    <!-- Mobile -->
    <Button iconOnly title="Search" class="!bg-transparent block md:hidden">
      <SearchIcon size={21} />
    </Button>
    <Button iconOnly title="Options" class="!bg-transparent block md:hidden">
      <MenuIcon size={21} />
    </Button>
    <!-- Desktop -->
    <Button
      iconOnly
      title="Server"
      class="md:flex hidden items-center gap-x-1 px-3 bg-neutral-800 hover:bg-neutral-900"
    >
      <ServerIcon size={20} />
      <span class="hidden lg:inline">{"Server:"}</span>
      <span class="bg-green-500 size-2.5 rounded-md mx-0.5" />
      <strong>SponsorBlock</strong>
      <ChevronDownIcon size={18} />
    </Button>
    <Button
      iconOnly
      title="Watchlist"
      clickEvent={watchlistToggle.toggleState}
      class="hidden md:block"
    >
      <BookmarkIcon size={20} />
    </Button>
    <Button
      iconOnly
      title="Options"
      clickEvent={optionToggle.toggleState}
      class="hidden md:block"
    >
      <SettingsIcon size={20} />
    </Button>
  </div>
</nav>

<Watchlist />
<Options />

// src/components/base/Navbar.tsx
"use client"

import { LuBookmark, LuSearch, LuSettings } from "react-icons/lu"

import { _Link as Link } from "../Link"
import { NavbarOptions } from "./NavbarOptions"
import { useState } from "react"
import { NavbarSearch } from "./NavbarSearch"

export function Navbar() {
  const [searchToggle, setSearchDialogToggle] = useState(false)
  const [optionsToggle, setOptionDialogToggle] = useState(false)

  const toggleOptionDialog = () => setOptionDialogToggle(!optionsToggle)
  const toggleSearchDialog = () => setSearchDialogToggle(!searchToggle)

  return (
    <>
      <nav className="flex justify-between px-6 py-3">
        <div className="flex items-center gap-x-3">
          <Link
            href="/"
            className="no-underline font-extrabold text-xl"
            translate="no"
          >
            SponsorExplorer
          </Link>
          <button
            className="hidden md:flex px-2 py-1 w-60 gap-x-1.5 rounded-md border-2 border-red-200 items-center"
            onClick={toggleSearchDialog}
          >
            <LuSearch size={19} />
            <span className="opacity-50">Search</span>
          </button>
        </div>
        <div className="flex gap-x-1">
          <button
            className="p-2 rounded-md bg-red-200 hover:bg-red-300 block md:hidden"
            onClick={toggleSearchDialog}
          >
            <LuSearch size={20} />
          </button>
          <button className="p-2 rounded-md bg-red-200 hover:bg-red-300 hidden md:block">
            <LuBookmark size={20} />
          </button>
          <button
            className="p-2 rounded-md bg-red-200 hover:bg-red-300"
            onClick={toggleOptionDialog}
          >
            <LuSettings size={20} />
          </button>
        </div>
      </nav>
      <NavbarOptions open={optionsToggle} onClose={toggleOptionDialog} />
      <NavbarSearch open={searchToggle} onClose={toggleSearchDialog} />
    </>
  )
}
