// src/lib/components/Badges/LengthBadge.svelte
<script lang="ts">
  import Badge from "./Badge.svelte"
  import FastForwardIcon from "lucide-svelte/icons/fast-forward"
  import VolumeXIcon from "lucide-svelte/icons/volume-x"
  import SparklesIcon from "lucide-svelte/icons/sparkles"
  import Bookmark from "lucide-svelte/icons/bookmark"
  import { formatTimecode, cn } from "$lib/utils"

  export let actionType: string = "skip"
  export let startTime: number = 0
  export let endTime: number = 1

  const actionTypeIcons: any = {
    skip: FastForwardIcon,
    mute: VolumeXIcon
  }

  const calculatedLength = endTime - startTime

  const roundNum = (n: number) => n.toFixed(2)

  const segLength = `${formatTimecode(startTime)} – ${formatTimecode(endTime)}`
  const segCalculatedLength = `(${roundNum(calculatedLength)}s)`

  const highlightTimecode = formatTimecode(startTime, {
    includeMilliseconds: true
  })

  const ICON_SIZE = 18
</script>

<Badge
  class={cn(
    actionType === "poi" ? "bg-pink-900" : "bg-neutral-900",
    "rounded-2xl inline-flex items-center gap-x-1.5 py-0.5 [&_span]:text-sm"
  )}
>
  {#if actionType === "skip" || actionType === "mute"}
    <svelte:component this={actionTypeIcons[actionType]} size={ICON_SIZE} />
    <span>{segLength}</span>
    <span class="opacity-75">{segCalculatedLength}</span>
  {:else if actionType === "full"}
    <SparklesIcon size={ICON_SIZE} />
    <span class="font-bold">Full Video Label</span>
  {:else if actionType === "poi"}
    <SparklesIcon size={ICON_SIZE} />
    <span>{highlightTimecode}</span>
  {:else if actionType === "chapter"}
    <Bookmark size={ICON_SIZE} />
    <span>{segLength}</span>
    <span class="opacity-75">{segCalculatedLength}</span>
  {/if}
</Badge>

// client/src/components/Badges/LengthBadge.tsx
import type { VideoSegments } from "@/types"
import { formatTimecode } from "@/utils"
import {
  LuFastForward as SkipIcon,
  LuVolumeX as MuteIcon,
  LuSparkles as HighlightIcon,
  LuBookmark as ChapterIcon,
  LuVideo as FullIcon,
} from "react-icons/lu"

type LengthProps = Pick<
  VideoSegments["segments"][number],
  "actionType" | "startTime" | "endTime"
>

interface LengthBadgeProps extends LengthProps {}

export function LengthBadge(props: LengthBadgeProps) {
  const timecodeOptions = {
    includeMilliseconds: true,
    msRoundFactor: 3,
  } satisfies Parameters<typeof formatTimecode>[1]

  const segmentLength = (props.endTime - props.startTime).toFixed(2)

  return (
    <span className="whitespace-nowrap inline-flex items-center gap-x-1.5">
      <div>
        {props.actionType === "skip" ? <SkipIcon size={19} /> : null}
        {props.actionType === "mute" ? <MuteIcon size={19} /> : null}
        {props.actionType === "full" ? <FullIcon size={19} /> : null}
        {props.actionType === "poi" ? <HighlightIcon size={19} /> : null}
        {props.actionType === "chapter" ? <ChapterIcon size={19} /> : null}
      </div>
      {props.actionType === "full" ? (
        <span>Full video label</span>
      ) : (
        <div className="inline-flex gap-x-1 items-center">
          <span>{formatTimecode(props.startTime, timecodeOptions)}</span>
          {props.actionType !== "poi" ? (
            <>
              <span>{` – `}</span>
              <span>{formatTimecode(props.endTime, timecodeOptions)}</span>
              <span className="text-sm">({`${segmentLength}s`})</span>
            </>
          ) : null}
        </div>
      )}
    </span>
  )
}
