// src/lib/components/Notice.svelte
<script lang="ts">
  import InfoIcon from "lucide-svelte/icons/info"
  import WarningIcon from "lucide-svelte/icons/triangle-alert"
  import AlertIcon from "lucide-svelte/icons/circle-x"
  import type { IconProps } from "lucide-svelte"

  import { cva, type VariantProps } from "class-variance-authority"

  const noticeEl = cva("flex items-center gap-x-2.5 rounded-md px-3.5 py-2.5", {
    variants: {
      intent: {
        info: "bg-blue-950",
        warn: "bg-yellow-950",
        alert: "bg-red-950"
      }
    },
    compoundVariants: [
      {
        intent: "info"
      }
    ]
  })

  interface $$Props extends VariantProps<typeof noticeEl> {
    heading: string
  }

  type NoticeIntent = NonNullable<$$Props["intent"]>

  const fallbackHeadingLabel = {
    info: "Info",
    alert: "Alert",
    warn: "Warning"
  }

  const iconProps: IconProps = {
    size: 24,
    class: "flex-shrink-0"
  }

  export let intent: $$Props["intent"] = "info"
  export let heading: string = fallbackHeadingLabel[intent as NoticeIntent]
</script>

<div
  class={noticeEl({
    intent
  })}
>
  {#if intent === "info"}
    <InfoIcon {...iconProps} />
  {:else if intent === "warn"}
    <WarningIcon {...iconProps} />
  {:else}
    <AlertIcon {...iconProps} />
  {/if}
  <div>
    <div class="font-bold text-lg pb-0.5">{heading}</div>
    <span>
      <slot />
    </span>
  </div>
</div>

// client/src/components/Notice.tsx
import { cva, type VariantProps } from "class-variance-authority"
import { type PropsWithChildren, useId } from "react"
import {
  LuInfo as InfoIcon,
  LuAlertTriangle as WarningIcon,
  LuXCircle as AlertIcon,
} from "react-icons/lu"

const NoticeBox = cva(
  "text-black dark:text-white flex items-center gap-x-2.5 rounded-md px-3.5 py-2.5",
  {
    variants: {
      intent: {
        info: "bg-blue-100 dark:bg-blue-800/30",
        warn: "bg-yellow-100 dark:bg-yellow-800/30",
        alert: "bg-red-100 dark:bg-red-800/30",
      },
    },
    compoundVariants: [
      {
        intent: "info",
      },
    ],
  },
)

interface NoticeProps {
  heading?: string
}

export function Notice(
  props: PropsWithChildren<NoticeProps & VariantProps<typeof NoticeBox>>,
) {
  const _id = useId()
  const a11yHeadingId = `notice-title-${_id}`

  const iconProps = {
    size: 26,
    className: "flex-shrink-0",
  }

  return (
    <div
      data-notice-box=""
      className={NoticeBox({
        intent: props.intent,
      })}
      role="note"
      aria-labelledby={a11yHeadingId}
    >
      {props.intent === "info" && <InfoIcon {...iconProps} />}
      {props.intent === "warn" && <WarningIcon {...iconProps} />}
      {props.intent === "alert" && <AlertIcon {...iconProps} />}
      <div>
        <div className="font-semibold text-lg pb-0.5" id={a11yHeadingId}>
          {props.heading}
        </div>
        <span>{props.children}</span>
      </div>
    </div>
  )
}
